version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./training_data:/app/training_data
      - ./chat_history:/app/chat_history
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - PORT=5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Frontend service
  frontend:
    build:
      context: /volume1/docker/CodeBuddy/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /volume1/docker/CodeBuddy/frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - BACKEND_URL=http://192.168.1.5000:5000
    depends_on:
      - backend




version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./.env
    restart: unless-stopped